apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinador
  labels:
    app: coordinador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinador
  template:
    metadata:
      labels:
        app: coordinador
    spec:
      containers:
        - name: coordinador
          image: facundootero/coordinador:latest  # Usar la última versión
          imagePullPolicy: Always  # Siempre descargar la última versión
          ports:
            - containerPort: 5000
                     
          resources:   # ✅ Limites de CPU y memoria
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:  # ✅ Verifica si está vivo, si falla lo reinicia
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:  # ✅ Verifica si está listo para recibir tráfico
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
      
---
apiVersion: v1
kind: Service
metadata:
  name: coordinador-integrador
spec:
  type: LoadBalancer
  selector:
    app: coordinador
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
