apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-integrador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
        requests:
          memory: "128Mi"  # Reducido de 256Mi a 128Mi
          cpu: "250m"      # Reducido de 500m a 250m
        limits:
          memory: "256Mi"  # Reducido de 512Mi a 256Mi
          cpu: "500m"      # Reducido de 1 CPU a 500m

        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-integrador
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
