apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-cpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-cpu
  template:
    metadata:
      labels:
        app: worker-cpu
    spec:
      containers:
      - name: worker-cpu
        image: facundootero/worker-cpu:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: COORDINATOR_URL
          value: "http://coordinador-integrador:5000/solved_task"
        resources:  # ✅ `resources` ahora está fuera de `env`, en el nivel correcto
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
