apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pool
spec:
  replicas: 3  # Número de workers en el pool
  selector:
    matchLabels:
      app: worker-pool
  template:
    metadata:
      labels:
        app: worker-pool
    spec:
      containers:
      - name: worker-pool
        image: facundootero/worker-pool:latest  # Nombre de la imagen en Docker Hub
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: COORDINATOR_URL
          value: "http://coordinador-integrador:5000/solved_task"
        - name: QUEUE_NAME
          value: "QueueTransactions"
        - name: EXCHANGE_BLOCK
          value: "ExchangeBlock"
        - name: NUM_WORKERS
          value: "2"
        resources:
          limits:
            cpu: "100m"
            memory: "20Mi"
          requests:
            cpu: "100m"
            memory: "20Mi"
