name: 🔧 Setup básico

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Obtener el repositorio
        uses: actions/checkout@v2

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 🔐 Autenticar con Google Cloud
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > ${{ github.workspace }}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
