name: 🧱 Despliegue con Terraform

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🚀 Inicializar y aplicar Terraform
        working-directory: "TPFinal/Infraestructura/terraform servicios"
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > credentials.json
          terraform init
          terraform apply -auto-approve
