name: 🐳 Construcción y Push de Imágenes Docker
on:
  push:
    branches:
      - main
    paths:
      - 'TPFinal/blockchain/Coordinador/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 🐳 Build & Push Coordinador
        run: |
          docker build -f TPFinal/blockchain/Coordinador/dockerfile.dockerfile -t facundootero/coordinador:latest TPFinal/blockchain/Coordinador
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push facundootero/coordinador:latest
