name: 📈 Despliegue de Monitorización (Prometheus & Grafana)

on:
  workflow_call:

jobs:
  monitoreo:
    runs-on: ubuntu-latest
    steps:
      - name: 🔐 Obtener credenciales de GKE
        run: |
          gcloud container clusters get-credentials cluster-integrador --zone us-east1-c --project sdypp082025
          kubectl get nodes

      - name: 🧹 Eliminar instalación previa (si existe)
        run: |
          helm uninstall prometheus -n default || true
          kubectl delete clusterrolebinding -l app.kubernetes.io/instance=prometheus --ignore-not-found
          kubectl delete clusterrole -l app.kubernetes.io/instance=prometheus --ignore-not-found

      - name: 📦 Instalar Prometheus con Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack             -n monitoring --create-namespace

      - name: 🌐 Exponer Prometheus por LoadBalancer
        run: |
          kubectl expose deploy prometheus-kube-prometheus-prometheus             --type=LoadBalancer --name=prometheus-lb || true
