name: Terraform and Kubernetes Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'



    - name: Authenticate with Google Cloud
      run: |
              echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > ${{ github.workspace }}/gcloud-key.json
              gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
  
    - name: Configurar el proyecto en Google Cloud
      run: |
                gcloud config set project sdyppfinal2025
                gcloud config set compute/zone us-east1-c
                gcloud config set compute/region us-east1

    - name: Instalar gke-gcloud-auth-plugin manualmente
      run: |
                    echo "🔹 Instalando gke-gcloud-auth-plugin..."
                    export CLOUD_SDK_REPO="cloud-sdk"
                    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
                    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
                    sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
                    echo "✅ Plugin instalado correctamente."
          
         
    - name: Configurar kubectl con credenciales de GKE
      run: |
                        echo "🔹 Obteniendo credenciales del clúster de GKE..."
                        gcloud container clusters get-credentials cluster-integrador --zone us-east1-c --project sdyppfinal2025
                        kubectl config current-context
              
      
    - name: Asignar permisos a la cuenta predeterminada de Compute Engine
      run: |
                            COMPUTE_SA="105059060773-compute@developer.gserviceaccount.com"
                            
                            echo "🛠️ Asignando permisos de storage.objectAdmin a $COMPUTE_SA..."
                            gcloud storage buckets add-iam-policy-binding gs://bucket_integrador_final2025 \
                              --member="serviceAccount:$COMPUTE_SA" \
                              --role="roles/storage.objectAdmin"
                  
                            echo "🛠️ Asignando permisos de storage.admin a $COMPUTE_SA..."
                            gcloud projects add-iam-policy-binding sdyppfinal2025 \
                              --member="serviceAccount:$COMPUTE_SA" \
                              --role="roles/storage.admin"
                  
                            echo "✅ Permisos asignados correctamente a $COMPUTE_SA."
                  
                  








    - name: Install dependencies (Coordinador)
      run: |
        python -m pip install --upgrade pip
        pip install -r TPFinal/blockchain/Coordinador/requirements.txt

     # Verificar archivos en la carpeta Minero
    - name: List files in Minero
      run: |
       ls TPFinal/blockchain/Minero

   # Instalar dependencias en la carpeta Minero
    - name: Install dependencies (Minero)
      run: |
       python -m pip install --upgrade pip
       pip install -r TPFinal/blockchain/Minero/requirements.txt

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Authenticate with Google Cloud (Coordinador)
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_COORDINADOR }}
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS_COORDINADOR }}' > credentials.json
   

  



        



     # Setup de CLI de Terraform
    - name: Terraform setup
      uses: hashicorp/setup-terraform@v3
    
    - name: Verificar y crear bucket en GCS si no existe
      run: |
          BUCKET_NAME="bucket_integrador_final2025"
          PROJECT_ID="sdyppfinal2025"
          REGION="us-east1"

          if ! gsutil ls -b gs://$BUCKET_NAME 2>/dev/null; then
            echo "El bucket no existe, creando..."
            gsutil mb -p $PROJECT_ID -c STANDARD -l $REGION gs://$BUCKET_NAME
          else
            echo "El bucket ya existe."
          fi


    - name: Terraform init
      working-directory: "TPFinal/Infraestructura/terraform servicios"
      env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
      run: |
          echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > credentials.json
    
          ls -lah

            BUCKET_NAME="bucket_integrador_final2025"
            PREFIX="cluster/state"

            terraform init --reconfigure \
              --backend-config "bucket=${BUCKET_NAME}" \
              --backend-config "prefix=${PREFIX}"
            
            terraform import google_compute_network.main projects/sdyppfinal2025/global/networks/main || true
            terraform import google_compute_address.nat projects/sdyppfinal2025/regions/us-east1/addresses/nat || true
            terraform import google_compute_firewall.allow-ssh projects/sdyppfinal2025/global/firewalls/allow-ssh || true
            terraform import google_service_account.kubernetes projects/sdyppfinal2025/serviceAccounts/kubernetes@sdyppfinal2025.iam.gserviceaccount.com || true
           
            terraform validate

            terraform plan -lock=false

            terraform apply -lock=false --auto-approve
      continue-on-error: true
      # - name: Initialize Terraform
      # working-directory: "TPFinal/Infraestructura/terraform servicios"
      # run: terraform init
      
    # - name: Plan Terraform changes
    #   working-directory: "TPFinal/Infraestructura/terraform servicios"
    #   run: terraform plan

    # - name: Apply Terraform changes
    #   if: github.ref == 'refs/heads/main'
    #   working-directory: "TPFinal/Infraestructura/terraform servicios"
    #   run: terraform apply -auto-approve
   

    - name: Build and Push Docker Image (Coordinador)
      run: |
        docker build -f TPFinal/blockchain/Coordinador -t facundootero/coordinador:latest TPFinal/blockchain/Coordinador
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push facundootero/coordinador:latest







    - name: Build Docker Images (Minero)
      run: |
          docker build -f TPFinal/blockchain/Minero/worker_cpu.dockerfile -t worker-cpu-app TPFinal/blockchain/Minero
    # docker build -f TPFinal/blockchain/Minero/worker_gpu.dockerfile -t worker-gpu-app TPFinal/blockchain/Minero
      
    # - name: Authenticate with Google Cloud
    #   env:
    #         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
    #   run: |
    #         echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > credentials.json
    
    # Configuración de kubectl para interactuar con el clúster de GKE
    # - name: Authenticate with Google Cloud
    #   run: |
    #     echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" > ${{ github.workspace }}/gcloud-key.json
    #     gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcloud-key.json
    #     gcloud config set project sdypp2025
    #     gcloud config set compute/zone us-east1-c
    #     gcloud config set compute/region us-east1
   
              
  
  #  # Despliegue de RabbitMQ en Kubernetes
  #   - name: Deploy RabbitMQ to Kubernetes
  #     run: |
  #           kubectl apply -f TPFinal/Infraestructura/k8s/rabbit-deploy.yaml
  # #  # Verificación de que RabbitMQ está corriendo y tiene IP pública
  # #   - name: Verify RabbitMQ Service
  # #     run: |
  # #           kubectl get services rabbitmq
  #   - name: Verificar estado de RabbitMQ
  #     run: |
  #       kubectl get pods
  #       kubectl get services rabbitmq
    
    
  
    - name: Instalar gke-gcloud-auth-plugin manualmente
      run: |
          export CLOUD_SDK_REPO="cloud-sdk"
          echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Obtener credenciales de GKE
      run: |
          gcloud container clusters get-credentials cluster-integrador --zone us-east1-c --project sdyppfinal2025
          kubectl get nodes

    - name: Aplicar Deployment de RabbitMQ en Kubernetes
      run: |
          kubectl apply --validate=false -f TPFinal/Infraestructura/k8s/rabbit-deploy.yaml

    - name: Aplicar Deployment de Redis en Kubernetes
      run: |
              kubectl apply --validate=false -f TPFinal/Infraestructura/k8s/redis-deploy.yaml
    
    - name: Verificar estado de Redis
      run: |
              kubectl get pods
              kubectl get services redis-integrador
    
    
    - name: Apply Kubernetes Deployment (Coordinador)
      run: |
                kubectl apply -f TPFinal/Infraestructura/k8s/coordinador-deploy.yaml
                kubectl rollout restart deployment coordinador  # Reiniciar el despliegue para tomar la nueva imagen
            
        

    - name: Obtener IP pública del Coordinador
      run: |
                  echo "Esperando a que se asigne la IP pública al Coordinador..."
                  for i in {1..10}; do
                      IP=$(kubectl get service coordinador-integrador -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
                      if [[ -n "$IP" ]]; then
                          echo "IP pública del Coordinador: $IP"
                          echo "COORDINADOR_IP=$IP" >> $GITHUB_ENV
                          break
                      fi
                      echo " Aún no se asignó la IP, reintentando en 10 segundos..."
                      sleep 10
                  done
                   