name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infraestructura con Terraform
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Clonar el repositorio
        uses: actions/checkout@v3

      - name: ☁️ Instalar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 453.0.0'

      - name: 🔐 Autenticarse en Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 📂 Seleccionar proyecto y región
        run: |
          gcloud config set project sdypp082025
          gcloud config set compute/region us-east1-c
          gcloud config set compute/zone us-east1-c

      - name: 🧱 Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: ⚙️ Inicializar Terraform
        run: terraform init

      - name: ✅ Validar Terraform
        run: terraform validate

      - name: 🔍 Plan de Terraform
        run: terraform plan -lock=false

      - name: 🚀 Aplicar Terraform
        run: terraform apply -lock=false --auto-approve
